services:
  loongson_devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # container_name: loongson_dev
    network_mode: host

    volumes:
      - ..:/workspace:cached
      - ../ls_2k0300_env:/opt/ls_2k0300_env:cached,ro
    working_dir: /workspace
    command: /bin/sh -c "tail -f /dev/null"